Only process secrets if openvpn feature is enabled
Fixes #25

diff --git a/hooks/secrets b/hooks/secrets
--- a/hooks/secrets
+++ b/hooks/secrets
@@ -7,35 +7,47 @@ prefix=secret/$GENESIS_VAULT_PREFIX
 case $GENESIS_SECRET_ACTION in
 check)
   rc=0
-  if ! safe --quiet check $prefix/openvpn/certs/ca; then
-    echo "[openvpn/certs/ca] is missing"
-    rc=1
+  if want_feature openvpn ; then
+    if ! safe --quiet check $prefix/openvpn/certs/ca; then
+      echo "[openvpn/certs/ca] is missing"
+      rc=1
+    fi
+    if ! safe --quiet check $prefix/openvpn/certs/server; then
+      echo "[openvpn/certs/server] is missing"
+      rc=1
+    fi
+
+    [[ $rc == 0 ]] && echo "All secrets and certs present!"
+    exit $rc
+  else
+    echo "No secrets needed (openvpn feature not selected)"
   fi
-  if ! safe --quiet check $prefix/openvpn/certs/server; then
-    echo "[openvpn/certs/server] is missing"
-    rc=1
-  fi
-  
-  [[ $rc == 0 ]] || exit $rc
-  echo "All secrets and certs present!"
   ;;
 
 add)
-  if ! safe --quiet check $prefix/openvpn/certs/ca; then
-    echo "[openvpn/certs/ca] generating new openvpn ca certificate"
-    safe --quiet x509 issue --ca --name ca.openvpn -u crl_sign -u key_cert_sign $prefix/openvpn/certs/ca
-  fi
-  if ! safe --quiet check $prefix/openvpn/certs/server; then
-    echo "[openvpn/certs/server] generating new openvpn server certificate"
-    safe --quiet x509 issue --signed-by $prefix/openvpn/certs/ca --name server.openvpn --ttl 180d -u server_auth -u digital_signature -u key_encipherment $prefix/openvpn/certs/server
+  if want_feature openvpn ; then
+    if ! safe --quiet check $prefix/openvpn/certs/ca; then
+      echo "[openvpn/certs/ca] generating new openvpn ca certificate"
+      safe --quiet x509 issue --ca --name ca.openvpn -u crl_sign -u key_cert_sign $prefix/openvpn/certs/ca
+    fi
+    if ! safe --quiet check $prefix/openvpn/certs/server; then
+      echo "[openvpn/certs/server] generating new openvpn server certificate"
+      safe --quiet x509 issue --signed-by $prefix/openvpn/certs/ca --name server.openvpn --ttl 180d -u server_auth -u digital_signature -u key_encipherment $prefix/openvpn/certs/server
+    fi
+  else
+    echo "No secrets needed (openvpn feature not selected)"
   fi
   ;;
 
 rotate)
-  echo "[openvpn/certs/ca] rotating openvpn ca certificate"
-  safe --quiet x509 issue --ca --name ca.openvpn -u crl_sign -u key_cert_sign $prefix/openvpn/certs/ca
-  echo "[openvpn/certs/server] rotating openvpn server certificate"
-  safe --quiet x509 issue --signed-by $prefix/openvpn/certs/ca --name server.openvpn --ttl 180d -u server_auth -u digital_signature -u key_encipherment $prefix/openvpn/certs/server  
+  if want_feature openvpn ; then
+    echo "[openvpn/certs/ca] rotating openvpn ca certificate"
+    safe --quiet x509 issue --ca --name ca.openvpn -u crl_sign -u key_cert_sign $prefix/openvpn/certs/ca
+    echo "[openvpn/certs/server] rotating openvpn server certificate"
+    safe --quiet x509 issue --signed-by $prefix/openvpn/certs/ca --name server.openvpn --ttl 180d -u server_auth -u digital_signature -u key_encipherment $prefix/openvpn/certs/server
+  else
+    echo "No secrets needed (openvpn feature not selected)"
+  fi
   ;;
 
 default)
